<?php echo $this->doctype(); ?>
<!-- Website Template by freewebsitetemplates.com -->
<html lang="de">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('League of Legends Tournament - RWTH Gaming Group')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath('/img/rwthgg_icon.png')))
                    ->prependStylesheet($this->basePath() . '/css/ggac.css') ?>

    <!-- Scripts -->
	<?php $this->bower('ggac', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
	<?php $this->bower('ieLT9', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
	<?php echo $this->headScript()->appendFile($this->basePath() . '/js/iconselect.js'); ?> 
</head>
<body>
	<div id="background">
		<div id="header">
			<div>
				<div>
					<a href="<?php echo $this->url('home') ?>" class="logo"><img src="<?= $this->basePath(); ?>/img/logo.png" alt=""></a>
					<?php echo $this->navigation('tournament_navigation')
									->menu()
									->setMinDepth(0)
									->setMaxDepth(0)
									->setonlyActiveBranch(false)
									->setUlClass('')
									->setPartial('partial/site_navigation.phtml')
									->render(); ?>
				</div>
			</div>
		</div>
		<div id="body">
			<div>
				<div>
					<?php echo $this->loginWidget()->render(); ?>
		            <?php echo $this->content; ?>
				</div>
			</div>
		</div>
		<div id="footer">
			<div>
				<ul>
					<li id="facebook"> <!-- Turniergruppe -->
						<a target="_blank" href="https://www.facebook.com/groups/202575866781327/">facebook</a>
					</li>
					<li id="googleplus"> <!-- RWTHGG Facebookseite -->
						<a target="_blank" href="https://www.facebook.com/rwthgg">RWTH Gaming Group</a>
					</li>
					<!--<li id="bitstars">
						<a target="_blank" href="http://www.bitstars.com">Bitstars</a>
					</li>-->
					<!--li id="fachschaft">
						<a target="_blank" href="http://www.fsmpi.rwth-aachen.de">Fachschaft</a>
					</li-->					
				</ul>
				<p>
					Events managed by the RWTH Gaming Group, the RWTH Gaming Group itself and this page are not endorsed by Riot Games and do not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.
				</p>
			</div>
		</div>
	</div>
    <?php echo $this->inlineScript() ?>
</body>
</html>
