<?php
/* @var $tournament \GGACTournament\Entity\Tournament */
$tournament = $this->tournament;

?>

<?php foreach($tournament->getPhases() as $phase) : /* @var $phase \GGACTournament\Entity\TournamentPhase */ ?>
<h1>Phase <?= $phase->getNumber() ?> <?= $phase->getName() ?></h1>
	<?php foreach($phase->getGroups() as $group) : /* @var $group GGACTournament\Entity\Group */ ?>
		<h2>Gruppe <?= $group->getNumber() ?></h2>
		<?php foreach($group->getRounds() as $round): /* @var $round \GGACTournament\Entity\Round */ ?>
			<h3>Runde <?= $round->getNumber() ?> (<?= $round->getRoundType() ?>) <?= $round->getIsHidden() ? '<i>versteckt</i>' : '' ?></h3>

			<?php foreach ($round->getMatches() as $match): /* @var $match \GGACTournament\Entity\Match */ ?>
				<?php
					$pointsHome = "";
					$pointsGuest = "";
					$hasConflict = false;
					$screensMissing = false;
					$matchHasResult = false;
					foreach($match->getGames() as $game){ /* @var $game \GGACTournament\Entity\Game */
						$blueIsHome = $match->getTeamHome() == $game->getTeamBlue();
						$isKampflos = ($game->getPointsBlue() !== null || $game->getPointsPurple() !== null) && ($game->getPointsBlue() === null || $game->getPointsPurple() === null);
						if($game->getPointsBlue() !== null || $game->getPointsPurple() !== null){
							$pointsHome  += $blueIsHome  ? $game->getPointsBlue() : $game->getPointsPurple();
							$pointsGuest += !$blueIsHome ? $game->getPointsBlue() : $game->getPointsPurple();
							$matchHasResult = true;
						}

						if($game->getMeldungHome() && empty($game->getScreenHome()) && empty($game->getScreenGuest()) && empty($game->getReport()) && !$isKampflos){
							$screensMissing = true;
						}
						if($game->getMeldungGuest() && empty($game->getScreenGuest()) && empty($game->getScreenHome()) && empty($game->getReport()) && !$isKampflos){
							$screensMissing = true;
						}
						if($game->getMeldungHome() !== null && $game->getMeldungGuest() !== null && $game->getMeldungHome() != $game->getMeldungGuest()){
							$hasConflict = true;
						}
					}

					$result = "";
					$result .= $pointsHome;
					$result .= " - ";
					$result .= $pointsGuest;
					$matchResult = $match->getPointsHome() . ' - ' . $match->getPointsGuest();
					if($match->getAnmerkung()){
						$matchResult = '<abbr title="'.$match->getAnmerkung().'">'.$matchResult.'</abbr>';
					}
					$result .= ' (' . $matchResult . ')';
					$hasResult = $matchHasResult || $match->getPointsHome() !== null || $match->getPointsGuest() !== null;

					$panelcls = 'panel-default';
					if($match->getIsBlocked() && !$screensMissing){
						$panelcls = 'panel-success';
					} elseif($hasConflict || $screensMissing){
						$panelcls = 'panel-danger';
					} elseif($pointsHome || $pointsGuest){
						$panelcls = 'panel-warning';
					}
				?>
				<div id="match_<?= $match->getId() ?>" class="panel <?= $panelcls ?> admin-paarung">
					<div class="panel-heading" data-toggle="collapse" data-target="#match_<?= $match->getId() ?> .panel-body" style="position: relative;">
						<div class="position"><?= $match->getNumber() ?></div>
						<div class="gamedate"><?= $match->getTime() ? $match->getTime()->format('m.d<\b\r>H:i') : '' ?></div>
						<div class="result">
							<?= $result ?><br>
							<?php if($match->getIsBlocked()) : ?>
							<a class="btn btn-xs" title="Doch nicht okay (unblock)" href="<?= $this->url('zfcadmin/matches/unblock', array('match_id' => $match->getId())) ?>">
								<i class="fa fa-undo"></i>
							</a>
							<?php elseif($hasResult) :  ?>
							<a class="btn btn-xs" title="Alles Okay (blockieren)" href="<?= $this->url('zfcadmin/matches/block', array('match_id' => $match->getId())) ?>">
								<i class="fa fa-check"></i>
							</a>
							<?php endif; ?>
							<a class="btn btn-xs" title="Ergebnis setzen und blockieren" href="<?= $this->url('zfcadmin/matches/setResult', array('match_id' => $match->getId())) ?>">
								<i class="fa fa-exclamation"></i>
							</a>
							<a class="btn btn-xs" title="Kommentieren (und nicht blockieren)" href="<?= $this->url('zfcadmin/matches/comment', array('match_id' => $match->getId())) ?>">
								<i class="fa fa-comments"></i>
							</a>
							<?php $btnCount = 0; ?>
							<?php if($hasConflict || $screensMissing) : $btnCount++; ?>
							<button class="btn btn-danger btn-xs" style="position: absolute;top: -9px;right: <?= - 9 + ($btnCount - 1) * 30 ?>px;" title="<?= $hasConflict ? 'Konflikt' : 'Screen fehlt' ?>"><i class="fa fa-info-circle"></i> </button>
							<?php endif; ?>
							<?php if(!empty($match->getAnmerkung())) : $btnCount++; ?>
							<button class="btn btn-info btn-xs" style="position: absolute;top: -9px;right: <?= - 9 + ($btnCount - 1) * 30 ?>px;" title="<?= $match->getAnmerkung() ?>"><i class="fa fa-comments"></i> </button>
							<?php endif; ?>
						</div>
						<?php
						$teamOptions = array(
							'showFarberwartung' => true,
							'useBootstrap' => true,
							'showWarnings' => true,
							'playerOptions' => array(
								'showCaptain' => true,
								'showCaptainContact' => true,
								'showAllContacts' => false,
								'emailWithLink' => true,
								'showWins' => false
							)
						);
						echo $this->partial('ggac-tournament/partial/team.phtml', array('team' => $match->getTeamHome(),  'match' => $match) + $teamOptions);
						echo $this->partial('ggac-tournament/partial/team.phtml', array('team' => $match->getTeamGuest(), 'match' => $match) + $teamOptions);
						?>
						<div style="clear: both;"></div>
					</div>
					<div class="panel-body collapse">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Nr</th>
									<th><abbr title="Meldung Heim">MeldH</abbr></th>
									<th><abbr title="Screen Heim">ScrH</abbr></th>
									<th><abbr title="Meldung Gast">MeldG</abbr></th>
									<th><abbr title="Screen Gast">ScrG</abbr></th>
									<th><abbr title="Ergebnis">Erg</abbr></th>
								</tr>
							</thead>

							<tbody>
								<?php $anmerkungHome = ''; $anmerkungGuest = ''; ?>
								<?php foreach($match->getGames() as $game) : ?>
									<?php
										if($game->getAnmerkungHome()){
											$anmerkungHome .= ($anmerkungHome ? '<br>' : '') .$game->getAnmerkungHome();
										}
										if($game->getAnmerkungGuest()){
											$anmerkungGuest .= ($anmerkungHome ? '<br>' : '') .$game->getAnmerkungGuest();
										}
										
										$isKampflos = ($game->getPointsBlue() !== null || $game->getPointsPurple() !== null) && ($game->getPointsBlue() === null || $game->getPointsPurple() === null);

										$blue = $game->getPointsBlue();
										$purple = $game->getPointsPurple();
										if($isKampflos && $blue === null){
											$blue = '-';
										} elseif ($isKampflos){
											$purple = '-';
										}
										$ergebnis  = $match->getTeamHome()  == $game->getTeamBlue() ? $game->getPointsBlue() : $game->getPointsPurple();
										$ergebnis .= ' - ';
										$ergebnis .= $match->getTeamGuest() == $game->getTeamBlue() ? $game->getPointsBlue() : $game->getPointsPurple();
									?>
									<tr>
										<td class="cell cell-nr"><?= $game->getNumber() ?></td>
										<td class="cell cell-meldung-heim"><?= $game->getMeldungHome() ?></td>
										<td class="cell cell-screen-heim"><?php if($game->getScreenHome()): ?><a data-lightbox="game_<?= $game->getId() ?>_H" data-title="<?= $match->getTeamHome() ? $match->getTeamHome()->getName() : 'Spielfrei' ?> - <?= $match->getTeamGuest() ? $match->getTeamGuest()->getName() : 'Spielfrei' ?>: Spiel <?= $game->getNumber() ?>" href="<?= $this->basePath($game->getScreenHome()) ?>">Screen</a><?php endif; ?></td>
										<td class="cell cell-meldung-gast"><?= $game->getMeldungGuest() ?></td>
										<td class="cell cell-screen-gast"><?php if($game->getScreenGuest()): ?><a data-lightbox="game_<?= $game->getId() ?>_H" data-title="<?= $match->getTeamHome() ? $match->getTeamHome()->getName() : 'Spielfrei' ?> - <?= $match->getTeamGuest() ? $match->getTeamGuest()->getName() : 'Spielfrei' ?>: Spiel <?= $game->getNumber() ?>" href="<?= $this->basePath($game->getScreenGuest()) ?>">Screen</a><?php endif; ?></td>
										<td class="cell cell-ergebnis"><?= $ergebnis ?></td>
									</tr>
								<?php endforeach; ?>
								<tr>
									<td class="cell cell-nr"></td>
									<td colspan="2" class="cell cell-anmerkung"><?= $anmerkungHome ?></td>
									<td colspan="2" class="cell cell-anmerkung"><?= $anmerkungGuest ?></td>
									<td class="cell cell-ergebnis"></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			<?php endforeach;?>
		<?php endforeach; ?>
	<?php endforeach; ?>
<?php endforeach; ?>