<?php $this->loginWidget(true)->setRedirect('registration/display'); ?>
<div class="games">
	<div class="content">
		<?php $singles = $this->singles; ?>
		<h3>Einzelanmeldungen<span style="padding-left: 5px; font-size: 10px;"><?= count($singles) ?> Spieler</span></h3>
		<ul>
			<li style="border: none">
				<?php if(count($singles) == 0) : ?>
					<p>Noch keine Anmeldungen vorhanden</p>
				<?php else : 
					foreach($singles as $registration){
						echo $this->partial('ggac-tournament/partial/player.phtml', array(
							'registration' => $registration,
						));
					}
				?>
				<?php endif; ?>
			</li>
		</ul>
	</div>
	<div class="aside">
		<?php $teams = $this->teams ?>
		<?php 
			$playerCount = 0; 
			foreach($teams as $team){
				$playerCount += count($team);
			}
		?>
		<h3>Teamanmeldungen<span style="padding-left: 5px; font-size: 10px;"><?= count($teams) ?> Teams/<?= $playerCount ?> Spieler</span></h3>
		<ul>
			<li style="border: none">
				<?php if(count($teams) == 0) : ?>
					<p>Noch keine Anmeldungen vorhanden</p>
				<?php else : 
					foreach($teams as $teamName => $players){
						echo $this->partial('ggac-tournament/registration/partial/team.phtml', array(
							'players' => $players,
							'teamName' => $teamName,
							'playerParams' => array(),
							'teamIcon' => $players[0]->getIcon(),
						));
					}
				?>
				<?php endif; ?>
			</li>
		</ul>
	</div>
</div>
