<?php
use GGACTournament\Form\RegistrationTeamForm;
use Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;
use GGACTournament\Entity\Registration;

?>

<div class="anmeldung">
	<div class="content">
		<ul>
			<?php echo $this->partial('partial/loginForm.phtml', array('loginForm' => $this->loginForm, 'formAction' => $this->url())) ?>
			<li>
				<div class="header">
					<?php if($this->team && is_array($this->team)) : ?>
					<b>Teamanmeldung zur RWTH Liga</b>
					<?php elseif($this->registration && $this->registration instanceof Registration) : ?>
					<b>Einzelanmeldung zur RWTH Liga</b>
					<?php else: ?>
					<b>Fehler</b>
					<?php endif; ?>
				</div>
				<div class="article">
					<?php if($this->team && is_array($this->team)) : ?>
					<b>Das Team <?php echo $this->team[0]->getTeamName() ?> wurde erfolgreich angemeldet</b>
					<?php elseif($this->registration && $this->registration instanceof Registration) : ?>
					<b>Hallo <?php echo $this->registration->getName() ?> "<?php echo $this->registration->getSummonerName() ?>", du hast dich erfolgreich zum Turnier angemeldet </b>
					<?php else: ?>
					<b>Bei der Anmeldung ist ein Fehler aufgetreten. Bitte versuche es erneut, oder kontaktiere die Turnierleitung.</b>
					<?php endif; ?>
				</div>
			</li>
		</ul>
	</div>
</div>