<?php

/* 
 * Copyright (C) 2016 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

?>

<h1>Team Matcher</h1>

<?php if($this->possible) : ?>
<h2>WARNUNG: Durch Klick auf den folgenden Button werden alle Teams gelöscht und die Teams werden neu geblidet!</h2>

<a href="<?php echo $this->url('zfcadmin/teams/match', array('confirm' => 'confirm')); ?>" class="btn btn-primary btn-lg btn-block">Teams bilden</a>

<?php elseif($this->ready): ?>
<h2>Teams erfolgreich gebildet</h2>
<?php else: ?>
<h2>Teams können nicht im laufenden Turnier geblidet werden</h2>
<?php endif; ?>