<?php

/* 
 * Copyright (C) 2016 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

?>
<div class="anmeldung teams">
	<div class="content">
		<ul>
			<?php echo $this->partial('partial/loginForm.phtml', array('loginForm' => $this->loginForm, 'formAction' => $this->url('teams'))) ?>
			<?php
				/* @var $tournament \GGACTournament\Entity\Tournament */
				$tournament = $this->tournament;
				$c = 0;
				foreach($tournament->getTeams() as $team): /* @var $team GGACTournament\Entity\Team */
					if($team->getIsBlocked()){
						continue;
					}
					$showContacts = $this->tournamentAcl('viewContacts', $team);
					$showCaptain = $this->tournamentAcl('viewCaptain', $team);
				?>
				<li style="margin-right: <?= (1 - $c % 2) * 20 ?>px; <?= $showCaptain ? "width: 920px; margin-right: 0px;" : '' ?> ">
					<div class="header" <?= $this->isAllowed('tournament', 'debug/moderator') && $team->hasCaptain() ? 'style="border-color: green;"' : '' ?>>
						<b><img style="width: 52px; vertical-align: middle; margin-right: 10px;" src="<?= $this->basePath("/img/teamIcons/".$team->getIcon()) ?>"><?php echo $team->getName() ?></b>
						<?= $this->isAllowed('debug', 'moderator') ? '<div style="clear: left">'.$team->getAnsprechpartner().'</div>' : ''; ?>
					</div>
					<div class="article">
						<div class="players">
							<?php $players = $team->getPlayers()->toArray(); ?>
							<?php usort($players, function($a, $b){return !$a->getIsCaptain() && !$b->getIsCaptain() ? 0 : ($a->getIsCaptain() ? -1 : 1); }) ?>
							<?php 
								foreach($players as $player){
									echo $this->partial('ggac-tournament/partial/player.phtml', array(
										'player' => $player,
										'addStyles' => $showCaptain ? '' : "min-height: 57px; padding-top: 0px;",
										'showCaptain' => true,
										'showCaptainContact' => $showCaptain,
										'showAllContacts' => $showContacts,
										'showWins' => true,
										'showEmailRight' => true
									));
								}; 
							?>
						</div>
					</div>
				</li>
				<?php
				$c++;
				endforeach;
			?>
			<li style="width: 920px; margin-right: 0px;">
				<div class="header">
					<b>Ersatzspieler</b>
				</div>
				<div class="article">
					<div class="players">
						<?php foreach($tournament->getSubs() as $player) : 
							echo $this->partial('ggac-tournament/partial/player.phtml', array(
								'player' => $player,
								'addStyles' => 'margin: 0  0 10px 0; ',
								'showCaptain' => false,
								'showCaptainContact' => false,
								'showAllContacts' => $this->tournamentAcl('viewSubContacts', $tournament),
								'showWins' => true,
								'showEmailRight' => true
							));
						endforeach; ?>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
