<?php
use GGACTournament\Entity\Team;

/* 
 * Copyright (C) 2016 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/* @var $tournament \GGACTournament\Entity\Tournament */
$tournament = $this->tournament;
$phase = $tournament->getCurrentPhase();
?>

<div class="anmeldung ergebnisse">
	<div class="content">
		<ul class="results">
			<?php
			$groupCount = count($phase->getGroups());
			foreach($phase->getGroups() as $group) : /* @var $group GGACTournament\Entity\Group */
			?>
			<li>
				<?php if($groupCount > 1) : ?>
				<div class="header">
					<b>Gruppe <?= $group->getNumber() ?></b>
				</div>
				<?php endif; ?> 
				
				<div class="article">
					<div class="standings">
						<?php
							$position = 0;
							$teams = $group->getTeams();
							usort($teams, array(Team::class, 'comparePoints'));
							foreach($teams as $team) : /* @var $team Team */
								if(!$team->hasCaptain())
									continue;
							?>
							<div class="standing <?= $position == 0 ? "first" : "" ?>">
								<div class="position"><?= $position + 1 ?></div>
								<?php foreach($team->getData()->getTiebreakOrder() as $tiebreak): ?>
								<div class="tiebreak <?php echo $tiebreak ?>"><?php echo ucwords(substr($tiebreak, 0, 5)) ?> <br> <?= $team->getData()->getTiebreak($tiebreak) ?></div>
								<?php endforeach; ?>
								<div class="score"><?= $team->getData()->getPoints() ?></div>
								
								<?php
									echo $this->partial('ggac-tournament/partial/team.phtml', array(
										'team' => $team,
										'showFarberwartung' => $this->isAllowed('debug', 'administrator'),
										'playerOptions' => array(
											'addStyles' => '',
											'showCaptain' => true,
											'showCaptainContact' => $this->tournamentAcl('viewCaptain', $team),
											'showAllContacts' => false,
											'showWins' => true
										),
									));
								?>
							</div>
							<?php
								$position++;
							endforeach;
						?>
					</div>
				</div>
			</li>
			<?php
			endforeach;
			?>
		</ul>
	</div>
</div>
