<?php 
/* @var $team \GGACTournament\Entity\Team */
$team = null;
/* @var $match \GGACTournament\Entity\Match */
$match = null;
$showWarnings = false;
$showScore = false;
$showFarberwartung = false;
$deleteWarningRoute = '';
$deleteWarningParams = array();
$playerOptions = array();

if(isset($this->team               )){ $team               = $this->team; }
if(isset($this->match              )){ $match              = $this->match; }
if(isset($this->showWarnings       )){ $showWarnings       = $this->showWarnings; }
if(isset($this->showScore          )){ $showScore          = $this->showScore; }
if(isset($this->showFarberwartung  )){ $showFarberwartung  = $this->showFarberwartung; }
if(isset($this->deleteWarningRoute )){ $deleteWarningRoute = $this->deleteWarningRoute; }
if(isset($this->deleteWarningParams)){ $deleteWarningParams= $this->deleteWarningParams; }
if(isset($this->playerOptions      )){ $playerOptions      = $this->playerOptions; }

$teamSide = '';
if($match != null){
	if($match->getTeamHome() == $team){
		$teamSide = ' home ';
	} elseif($match->getTeamHome() == $team){
		$teamSide = ' guest ';
	}
}

if($team != null) :
	$js = '';
	$playersId = '';
	if($match){
		$containerIds = array();
		if($match->getTeamHome()){
			$containerIds[] = "#players_".$match->getRound()->getNumber()."_".$match->getTeamHome()->getId();
		}
		if($match->getTeamGuest()){
			$containerIds[] = "#players_".$match->getRound()->getNumber()."_".$match->getTeamGuest()->getId();
		}

		$js = "var elms = $('".implode(", ", $containerIds)."'); if(elms.css('display') == 'block'){elms.css('display', 'none')} else {elms.css('display', 'block')}";
		$js = ' onclick="'.$js.'" ';

		$playersId = 'players_'.$match->getRound()->getNumber().'_'.$team->getId();
		$playersId = ' id="'.$playersId.'" ';
	} else {
		$containerIds = array();
		$containerIds[] = "#players_".$team->getId();
		$js = "var elms = $('".implode(", ", $containerIds)."'); if(elms.css('display') == 'block'){elms.css('display', 'none')} else {elms.css('display', 'block')}";
		$js = ' onclick="'.$js.'" ';

		$playersId = 'players_'.$team->getId();
		$playersId = ' id="'.$playersId.'" ';
	}

	$warnings = array();
	if($showWarnings){
		$warnings = $team->getWarnings();
	}
	?>
	<div class="team <?= $teamSide ?>" style="background-image: url('<?= $this->basePath('img/teamIcons/'.$team->getIcon()) ?>')">
		<div class="teamname" <?= $js ?>>
			<?= $team->getName() ?> 
			<?php if($team->getData()) : ?>
			(<?= $team->getData()->getPoints() ?>) 
			<?php endif; ?>
			<?= $showScore ? '('.$team->getScore().')' : '' ?> 
			<?= $showFarberwartung && $team->getData() ? $team->getData()->getFarberwartung() : '' ?>
			<?php foreach($warnings as $warning): 
				$warnJs = "if(confirm('Verwarnung löschen?')){ window.location='".$this->url($deleteWarningRoute, array('team_id' => $team->getId(), 'warning_id' => $warning->getId()) + $deleteWarningParams )."'; }";
			?>
			<img onclick="<?= $warnJs ?>" src="<?= $this->basePath() ?>/img/control/yellowcard.png" alt="<?= $warning->getComment(); ?>" title="<?= $warning->getComment(); ?>" style="height: 20px; vertical-align: top;">
			<?php endforeach; ?>
		</div>
		<div class="players" <?= $playersId ?>>
			<?php
				foreach($team->getPlayers() as $player):
					echo $this->partial('ggac-tournament/partial/player.phtml', array('player' => $player) + $playerOptions);
				endforeach;
			?>
		</div>
	</div>
<?php else : ?>
	<div class="team <?= $teamSide ?>">
		<div class="teamname">Spielfrei</div>
	</div>
<?php endif; ?>
